// import { Inter } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/MainLayout";
import MenuContextProvider from "@/context/MenuContext";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
            <body>
                <MenuContextProvider>
                    <MainLayout>{children}</MainLayout>
                </MenuContextProvider>
            </body>
        </html>
    );
}
